name = "Lorenz96andNDE"
uuid = "1c9eb66e-168a-43d5-8666-64b9f568c235"
authors = ["Lisa Kauck <lisa.kauck@tum.de"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
